# Workflow konfiguration
name: Hello World Workflow
description: Nur eine Demo

# Events
on: push

# Jobs (Aufgaben)
jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
             - name: Ziehe das Projekt
               uses: actions/checkout@v4.2.2
             
             - name: JavaScript ausführen
               run: node hello-world.js